Planpinterview/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Internal;
namespace Planpinterview.Models
{
    public class Player
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public DateTime date { get; set; }

        public int categprogramid { get; set; }
        public categprogram categprogram { get; set; }

        public double monyvalue { get; set; }
    }
}

Planpinterview/Models/result.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Planpinterview.Models
{
    public class result
    {
        [Key]
        public int id { get; set; }
        public DateTime from { get; set; }
        public DateTime to { get; set; }
        public double totalmony { get; set; }
        public int totalplayers { get; set; }
    }
}

Planpinterview/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Planpinterview.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Internal;
using System.Diagnostics;

namespace Planpinterview.Controllers
{
    public class PlayersController : Controller
    {
        private readonly appdbcontext _context;

        public PlayersController(appdbcontext context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            var appdbcontext = _context.players.Include(p => p.categprogram);
            return View(await appdbcontext.ToListAsync());
        }
       
        public async Task<IActionResult> Results()
        {
            ViewBag.totalmony = _context.players.Select(x=>x.monyvalue).Sum();
            var appdbcontext = _context.players.Include(p => p.categprogram);
            return View(await appdbcontext.ToListAsync());
        }

        public async Task<IActionResult> FilterResults(DateTime start,DateTime end)
        {

            var appdbcontext = _context.players.Where(x => x.date >= start && x.date <= end||x.date==start);

              
            return View(await appdbcontext.ToListAsync());
        }


        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.players
                .Include(p => p.categprogram)
                .FirstOrDefaultAsync(m => m.id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }
        [HttpGet]
        public ActionResult<double> getmonyvalueAsync(int? id)
        {
            //IEnumerable<double> mony = from m in _db.categprogram
            //           .Where(x => x.id == id)
            //           select m.monyvalue;
            if (id==null)
            {
                return BadRequest();
            }
            var mm = _context.categprogram.Where(x => x.id == id).FirstOrDefault().monyvalue;

            return  mm;
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            ViewData["categprogramid"] = new SelectList(_context.categprogram, "id", "name");
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,address,date,categprogramid,monyvalue")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["categprogramid"] = new SelectList(_context.categprogram, "id", "name", player.categprogramid);
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            ViewData["categprogramid"] = new SelectList(_context.categprogram, "id", "name", player.categprogramid);
            return View(player);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,address,date,categprogramid,monyvalue")] Player player)
        {
            if (id != player.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["categprogramid"] = new SelectList(_context.categprogram, "id", "name", player.categprogramid);
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.players
                .Include(p => p.categprogram)
                .FirstOrDefaultAsync(m => m.id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.players.FindAsync(id);
            _context.players.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.players.Any(e => e.id == id);
        }
    }
}

Planpinterview/Controllers/categprogramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Planpinterview.Models;

namespace Planpinterview.Controllers
{
    public class categprogramsController : Controller
    {
        private readonly appdbcontext _context;

        public categprogramsController(appdbcontext context)
        {
            _context = context;
        }

        // GET: categprograms
        public async Task<IActionResult> Index()
        {
            return View(await _context.categprogram.ToListAsync());
        }

        // GET: categprograms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categprogram = await _context.categprogram
                .FirstOrDefaultAsync(m => m.id == id);
            if (categprogram == null)
            {
                return NotFound();
            }

            return View(categprogram);
        }

        // GET: categprograms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: categprograms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,monyvalue")] categprogram categprogram)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categprogram);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categprogram);
        }

        public async Task<IActionResult> Createnewprogram([Bind("id,name,monyvalue")] categprogram categprogram)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categprogram);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categprogram);
        }

        // GET: categprograms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categprogram = await _context.categprogram.FindAsync(id);
            if (categprogram == null)
            {
                return NotFound();
            }
            return View(categprogram);
        }

        // POST: categprograms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,monyvalue")] categprogram categprogram)
        {
            if (id != categprogram.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categprogram);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!categprogramExists(categprogram.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categprogram);
        }

        // GET: categprograms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categprogram = await _context.categprogram
                .FirstOrDefaultAsync(m => m.id == id);
            if (categprogram == null)
            {
                return NotFound();
            }

            return View(categprogram);
        }

        // POST: categprograms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categprogram = await _context.categprogram.FindAsync(id);
            _context.categprogram.Remove(categprogram);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool categprogramExists(int id)
        {
            return _context.categprogram.Any(e => e.id == id);
        }
    }
}

Planpinterview/Views/Players/Create.cshtml
@model Planpinterview.Models.Player

@{
    ViewData["Title"] = "Create";
}

<h1>Add player</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label">Name</label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label">Address</label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="date" class="control-label">Date</label>
                <input asp-for="date" class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="categprogramid" class="control-label">Programe</label>
                <select asp-for="categprogramid" class ="form-control" asp-items="ViewBag.categprogramid">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="monyvalue" class="control-label">Price</label>
                <input asp-for="monyvalue" class="form-control" />
                <span asp-validation-for="monyvalue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add player" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section scripts{
                <script>


                    $(document).ready(function () {
                        $('#categprogramid').on('change', function () {
                            
                            $.ajax({
                                url: "/Players/getmonyvalue/" + $('#categprogramid').val(),
                                success: function (result) {
                                   
                                    result = JSON.parse(result);
                                    console.log(result);
                                    $('#monyvalue').val(result);
                                },
                                error: function () {
                                    $('#monyvalue').val("");
                                }
                            });
                        });
                    })
                </script>
}

Planpinterview/Views/Players/Delete.cshtml
@model Planpinterview.Models.Player

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.categprogram)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.categprogram.name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Planpinterview/Views/Players/Details.cshtml
@model Planpinterview.Models.Player

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.categprogram)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.categprogram.name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Planpinterview/Views/Players/Edit.cshtml
@model Planpinterview.Models.Player

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date" class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="categprogramid" class="control-label"></label>
                <select asp-for="categprogramid" class="form-control" asp-items="ViewBag.categprogramid"></select>
                <span asp-validation-for="categprogramid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="monyvalue" class="control-label"></label>
                <input asp-for="monyvalue" class="form-control" />
                <span asp-validation-for="monyvalue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Planpinterview/Views/Players/FilterResults.cshtml
@model IEnumerable<Planpinterview.Models.Player>

@{
    ViewData["Title"] = "FilterResults";
}

<h1>Results</h1>
<center>
    @using (Html.BeginForm("FilterResults", "Players", FormMethod.Post))
    {
        <span>start date:</span> <input type="date" name="start" />
        <span>End date:</span> <input type="date" name="end" />
        <input type="submit" asp-action="FilterResults"class="btn btn-success" value="Filter" />
        <br />
        <label> From @Html.TextBox("start", null, new { @class = "form-control datepicker" })</label>
        <label>To @Html.TextBox("end", null, new { @class = "form-control datepicker" })</label>
        <label id="totfilter" style="font-size:large">Total Mony= @Model.Select(x => x.monyvalue).Sum() </label>
        <label style="background-color:gainsboro;font-size:large"> Total Players= @Model.Select(x => x.id).Count() </label>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.address)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.categprogram)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.monyvalue)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.categprogram.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.monyvalue)
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    }
</center>

Planpinterview/Views/Players/Index.cshtml
@model IEnumerable<Planpinterview.Models.Player>

@{
    ViewData["Title"] = "Index";
}

<h1>Players</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Add player</a>
    <a asp-controller="categprograms" asp-action="Create" class="btn btn-primary">Add Program</a>
    <a asp-controller="Players" asp-action="Results" class="btn btn-primary">View Report</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.date)
            </th>
            <th>
                program
            </th>
            <th>
               Price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categprogram.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.monyvalue)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id" class="btn btn-primary">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id" class="btn btn-success">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Planpinterview/Views/Players/Results.cshtml
@model IEnumerable<Planpinterview.Models.Player>

@{
    ViewData["Title"] = "Results";
}

<h1>Results</h1>
<center>
    @using (Html.BeginForm("Results", "Players", FormMethod.Post))
    {
        <span style="background-color:darkgray" class="col-form-label-lg">start date:</span> <input type="date" name="start" class="border-bottom"/>
        <span style="background-color:darkgray" class="col-form-label-lg">End date:</span> <input type="date" name="end" />
        <input type="submit" style="width:100px" class="btn btn-success" asp-action="FilterResults" value="Filter"/>
        <label style="background-color:gainsboro"> Total Mony = @Model.Select(x => x.monyvalue).Sum() </label>
        <label style="background-color:gainsboro"> Total Players= @Model.Select(x => x.id).Count() </label>

        <table class="table">
            <thead>
                <tr>
                    <th>
                       Name
                    </th>
                    <th>
                       Address
                    </th>
                    <th>
                       Date
                    </th>
                    <th>
                       program
                    </th>
                    <th>
                       Price
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.categprogram.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.monyvalue)
                        </td>
                        
                    </tr>
                }
            </tbody>
        </table>
    }
</center>